KivSystemAdmin/aaasobo-management-system

frontend/src/app/components/SideNav.tsx

Revert highlighting user type on SideNav

---

README.md
backend/package.json

Resolves #4 
I wrote setup instructions to start development. I'm not sure if this is comprehensive, so please let me know if any additional steps should be taken or any information is missed.

Add setup to README.md

---

backend/src/controllers/instructorsController.ts
backend/src/routes/instructorsRouter.ts
backend/src/services/instructorsService.ts
frontend/src/app/components/elements/buttons/actionButton/ActionButton.module.scss
frontend/src/app/components/instructors-dashboard/instructor-profile/InstructorProfile.module.scss
frontend/src/app/components/instructors-dashboard/instructor-profile/InstructorProfile.tsx
frontend/src/app/helper/api/instructorsApi.ts

Implement editing instructor's profile function for admin dashboard
- Only admins can use the function (instructors are not allowed to update their profile by themselves)
- All items below can be updated:
Name, Nickname, Email, Class URL, Meeting ID, Passcode, and Self Introduction URL

Implement editing instructor's profile function for admin dashboard

---

frontend/src/app/components/customers-dashboard/profile/CustomerProfile.tsx
frontend/src/app/components/elements/inputField/InputField.tsx
frontend/src/app/components/instructors-dashboard/instructor-profile/InstructorProfile.tsx

Refactor the instructor's and customer's profile edit functions based on the review comments from the previous PR (#27).
Confirm that there are no issues or misunderstandings with both user profile edit functions.
[Instructor's profile edit page (example)]
http://localhost:3000/admins/instructor-list/1
[Customer's profile edit page (example)]
http://localhost:3000/admins/customer-list/1
1. Consider applying `useFormState` to simplify communications between the client and server sides.
Honestly, I still don’t fully understand how to use `useFormState` or how effective it is for our application. I need to study it more before using it.
Screenshot from PR #27 
2. Centralize Email Validation Logic
This logic is used not only for editing but also for login and registration. However, the …

Refactor customer and instructor profiles

---

backend/src/controllers/adminsController.ts
backend/src/routes/adminsRouter.ts
backend/src/services/adminsService.ts
frontend/src/app/admins/(authenticated)/admin-list/page.tsx
frontend/src/app/admins/(authenticated)/layout.tsx
frontend/src/app/components/admins-dashboard/UsersTable.tsx
frontend/src/app/components/customers-dashboard/profile/CustomerProfile.tsx
frontend/src/app/components/elements/inputField/InputField.tsx
frontend/src/app/components/instructors-dashboard/instructor-profile/InstructorProfile.tsx
frontend/src/app/helper/api/adminsApi.ts

Create admin list for admin dashboard.
Confirm that all admins registered on the database are visible on the list.
[Admin list]
http://localhost:3000/admins/admin-list
Discussions with the client are necessary to determine which features are needed:
1. Whether to include trash and edit functions in the list
2. Whether to create a profile page for each admin
3. Whether to allow an admin to edit other admins' information
4. The design of the side navbar icon

Create admin list

---

backend/src/controllers/adminsController.ts
backend/src/routes/adminsRouter.ts
backend/src/seed/dummy.ts
backend/src/services/classesService.ts

Update class list page (admin dashboard) based on the client's requirements (Monthly meeting in April) 
1. Fetch class information from 1 month ago to 1 month from now
2. Display instructors' nickname in "Instructor" column 
Note: `backend/src/seed/dummy.ts` was also updated because of the inquiry below
###
https://github.com/KivSystemAdmin/aaasobo-management-system/pull/63#issuecomment-2829047480
- Log in to the app as admin 
- Create regular classes for a specific customer (e.g., Alice)
- Access the class list page (http://localhost:3000/admins/class-list)
- Confirm that the points mentioned above are reflected correctly without any issues
- Set link in "ID" column to redirect to each class detail page (e.g., http://localhost:3000/admins/instructor-list/1/class-schedule/9)
- Implement a …

Update class list page

---

backend/prisma/prismaClient.ts

- Extend Prisma timeout to address the error encountered in the production environment (Vercel). 
- This PR is based on our Slack conversation below
===
I have conducted some research, and my current understanding is as follows:
**[Tentative solution]**
Extend the Prisma timeout more (e.g, from 10 seconds to 60 seconds)
###
**[Root cause]**
`addAvailabilityInternal` function (`backend/src/controllers/instructorsController.ts`) could not complete the entire process within 10 seconds (current Prisma timeout).
The screenshot shows the error occurred approximately 10 seconds after clicking the “Save” button on Instructor’s Schedule page.
###
**[Reasons]**
1. Vercel causes a latency (time delay) due to the geographical distance between clients, Vercel functions, and Neon (external database)
2. …

Extend Prisma timeout

---

backend/src/controllers/adminsController.ts
frontend/src/app/components/admins-dashboard/ListTable.module.scss
frontend/src/app/components/admins-dashboard/ListTable.tsx
frontend/src/app/helper/api/adminsApi.ts

1. Implement a scroll bar for each list page of admin dashboard
2. Rename some column names (e.g., from "Name" to "Plan" in plan list page)
3. Add "Class code" column to class list page
Note: Code review is not necessary as this PR contains only minor changes
1. Log in to the app as an admin user (email: `admin@example.com`, password: `AaasoBo!Admin`) 
2. Go to each list page
3. Confirm that a scrollbar appears when the screen size is reduced as shown below:

Add scroll bar to list pages

---

backend/src/controllers/adminsController.ts
frontend/src/app/components/admins-dashboard/ListTable.tsx
frontend/src/app/components/admins-dashboard/customers-dashboard/classCalendarForAdmin/CustomerDashboardClient.tsx
frontend/src/app/helper/data/navLinks.ts

This PR fixes a bug from #123, where the links in the ID column were not working (plus modifies some tiny features).
No need to confirm both behavior and code, just approving without any comment is fine.

Fix a bug in admin list page

---

frontend/src/app/components/admins-dashboard/events-dashboard/EventDashboardClient.tsx
frontend/src/app/components/admins-dashboard/events-dashboard/EventProfile.tsx
frontend/src/app/helper/api/eventsApi.ts
frontend/src/app/helper/types.d.ts

Fix frontend build bugs derived from #137 as shown below:

Fix build bug from PR#137

---

backend/package-lock.json
backend/package.json
backend/src/routes/usersRouter.ts
backend/src/test/users.test.ts
backend/vitest.config.mts

Resolve #143
This PR adds a testing framework to the backend.
**Purpose**
The goal of introducing tests is:
- To facilitate future changes: Tests help ensure we don't break existing features.
- To support complex scenarios: For example, features like adding a regular class can be tested more reliably.
This PR focuses on the user-related API (login and password reset), as it's a moderate starting point, in my opinion. It seems not too simple, not too complex.
**How to Run Tests**
Run `npm test` to execute the tests in users.test.ts.
All tests should pass. The database and Resend are mocked, so tests can run independently.
**Packages**
- Vitest: Testing framework
- supertest: Utility for testing Express apps (no need to listen() to the server)
**Auth Middleware Adjustment**
I noticed that …

Add user tests

---

backend/src/controllers/schedulesController.ts
backend/src/helper/dateUtils.ts
backend/src/routes/adminsRouter.ts
backend/src/seed/dummy.ts
backend/src/services/scheduleService.ts
frontend/src/app/actions/updateContent.ts
frontend/src/app/admins/(authenticated)/[id]/business-calendar/page.tsx
frontend/src/app/components/admins-dashboard/BusinessCalendarClient.tsx
frontend/src/app/components/admins-dashboard/BusinessCalendarForAdmin.tsx
frontend/src/app/components/admins-dashboard/BusinessCalendarModal.module.scss
frontend/src/app/components/admins-dashboard/BusinessCalendarModal.tsx
frontend/src/app/components/admins-dashboard/events-dashboard/EventProfile.tsx
frontend/src/app/helper/api/calendarsApi.ts
frontend/src/app/helper/types.d.ts
frontend/src/app/schemas/authSchema.ts

1. Implement schedule update function for business calendar page
2. Fix frontend build bug of event profile page
1. Log in to the app as an admin (e.g., email: `admin@example.com`, password: `AaasoBo!Admin`)
3. Go to the business calendar page (`http://localhost:3000/admins/1/business-calendar`)
4. Select one date or multiple dates and update events
5. Confirm that everything works correctly without any issues
- backend/src/controllers/schedulesController.ts
- frontend/src/app/actions/updateContent.ts
- frontend/src/app/components/admins-dashboard/BusinessCalendarClient.tsx
- frontend/src/app/components/admins-dashboard/BusinessCalendarModal.tsx
- Add a feature to update the color of all Sundays (Note: FullCalendar doesn't support selecting non-consecutive dates by default)
###
**[Select …

Implement business calendar update feature

---

backend/prisma/migrations/20250723165537_add_instructor_absence/migration.sql
backend/prisma/schema.prisma
backend/src/controllers/instructorAbsenceController.ts
backend/src/routes/instructorsRouter.ts
backend/src/seed/dummy.ts
backend/src/services/instructorAbsenceService.ts
backend/src/test/instructorAbsence.test.ts

Resolve #169 
This is the second PR for new instructor schedule system.
Add InstructorAbsence model with instructorId and absentAt fields.

Add InstructorAbsence table (new instructor schedule system 2)

---

backend/src/controllers/instructorScheduleController.ts
backend/src/routes/instructorsRouter.ts
backend/src/seed/dummy.ts
backend/src/services/instructorScheduleService.ts
backend/src/test/instructorSchedule.test.ts
frontend/src/app/components/admins-dashboard/instructors-dashboard/InstructorDashboardClient.tsx
frontend/src/app/components/admins-dashboard/instructors-dashboard/instructor-schedule/VersionedAvailabilityCalendar.tsx
frontend/src/app/components/features/calendar/Calendar.tsx
frontend/src/app/helper/api/instructorsApi.ts

Resolve #178 
Implement Instructor's Availability tab (WIP)
- This looks the same as Instructor's Availability tab
- Class and absence are not considered yet

Iimplement Instructor Availability tab (new instructor schedule system 4)

---

backend/prisma/migrations/20250728010152_change_instructor_schedule_dates_to_datetime/migration.sql
backend/prisma/migrations/20250728010831_migrate_instructor_schedule_to_datetime_with_jst_midnight/migration.sql
backend/prisma/schema.prisma
backend/src/controllers/instructorScheduleController.ts
backend/src/helper/dateUtils.ts
backend/src/seed/dummy.ts
backend/src/services/instructorScheduleService.ts
backend/src/test/instructorSchedule.test.ts

Change effectiveFrom and effectiveTo to DateTime (new instructor schedule system 5)

---

frontend/src/app/components/admins-dashboard/BusinessCalendarClient.tsx
frontend/src/app/helper/utils/calendarUtils.tsx

- Resolve a bug derived from https://github.com/KivSystemAdmin/aaasobo-management-system/pull/176#pullrequestreview-3058997383. 
- Refactor the business calendar component referred to https://github.com/KivSystemAdmin/aaasobo-management-system/pull/176#discussion_r2233687455

Fix color display bug

---

backend/src/controllers/adminsController.ts
backend/src/controllers/instructorsController.ts
backend/src/routes/instructorsRouter.ts
backend/src/services/classesService.ts
frontend/src/app/admins/(authenticated)/[id]/class-list/[classId]/page.tsx
frontend/src/app/admins/(authenticated)/[id]/class-list/page.tsx
frontend/src/app/admins/(authenticated)/[id]/instructor-list/[instructorId]/class-schedule/[classId]/page.tsx
frontend/src/app/components/instructors-dashboard/class-schedule/classDetails/ClassDetails.tsx
frontend/src/app/components/instructors-dashboard/class-schedule/classDetails/classItem/ClassItemForAdmin.tsx
frontend/src/app/helper/api/instructorsApi.ts
frontend/src/app/helper/types.d.ts
frontend/src/app/helper/utils/calendarUtils.tsx
frontend/src/app/instructors/[id]/class-schedule/[classId]/page.tsx

1. Enable access to each class details information from class list page
2. Update the bread crumb to make redirection correctly based on the previous pages
3. Change a column name from Time to JP Time in class list page
1. Log in to the app as admin (e.g., email: `admin@example.com`, password: `AaasoBo!Admin`)
2. Move to Class List page (e.g., `http://localhost:3000/admins/1/class-list`) and click one of `ID`
3. Confirm that everything including URL and bread crumb is displayed correctly and works without any issues (refer to image 1)
4. Go to instructor's "Class Schedule" tab (e.g., `http://localhost:3000/admins/1/instructor-list/1`) and click one of the slots on July 15th.
5. Confirm that everything including URL and bread crumb is displayed correctly and works without any issues (refer …

Enable to redirect to class details information for class list page

---

backend/src/controllers/adminsController.ts
frontend/src/app/admins/(authenticated)/[id]/business-calendar/page.tsx
frontend/src/app/components/admins-dashboard/BusinessCalendarClient.tsx
frontend/src/app/components/customers-dashboard/classes/ClassCalendar.tsx
frontend/src/app/components/features/calendarLegend/CalendarLegend.module.scss
frontend/src/app/components/instructors-dashboard/instructor-profile/InstructorProfile.tsx
frontend/src/app/helper/api/eventsApi.ts
frontend/src/app/schemas/authSchema.ts

1. Set name format validation for event registration and edit feature
2. Add the maximum number of characters limitation to text area fields of instructor profile component
3. Set legend in business calendar page as shown below
- Refactor the textarea component and unify it with the existing one

Set validation for event list page and instructor profile component etc

---

backend/src/middlewares/auth.middleware.ts
frontend/auth.config.ts

- Ability to decode the cookie in the backend and extract the user session (user type and ID)
- Add logic to verify that each operation is performed by the correct user
Note: Many frontend components will need to be updated
- Need to add `AUTH_SECRET` variable to both `frontend/.env` and `backend/.env` as follows:
E.g., `AUTH_SECRET`="C9jvuW+G3n+t2zD0iY6vg7iJhzh7P2bSLG7PxLR1fTg="

Update authentication logic (incomplete)

---

frontend/src/app/components/elements/UserStatusSwitcher/UserStatusSwitcher.tsx
frontend/src/app/helper/data/data.ts
frontend/src/app/helper/utils/dateUtils.ts

- Update the instructor leaving date restriction from 90 days prior to 1 month prior

Update instructor leaving date restriction

---

backend/src/controllers/schedulesController.ts
backend/src/routes/jobsRouter.ts
backend/src/server.ts
backend/src/test/helper.ts
backend/src/test/jobs.test.ts
shared/schemas/jobs.ts

Implement Zod schema on jobs router
